### ISSUE TITLE
Campo location do event

### ISSUE THREAD

**Issue by rodrigondec** [bti-imd/IntegraTI-API#12]
Na entidade event podemos ter o campo localização aberto e um campo endereço integrado com API de endereços do maps.

**Comment by Mazuh** [comment]
Saquei. Vou pesquisar um tamanho máximo pra string disso.

**Comment by rodrigondec** [comment]
Só uma sugestão que talvez seja legal. Pra colocar uma api do google maps mostrando o mapa do local no site

**Comment by Mazuh** [comment]
Eis um exemplo de código pra exibir a localização do CCSA, um prédio que fica ao lado dos setores I, V, biblioteca, coisa e tal. Há uma div vazia com id=map no HTML.

```js
function initMap() {
    var location = { lat: -5.8379134, lng: -35.1983559 }; /* CCSA administrative building */
    var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 17,
        center: location
    });
    var marker = new google.maps.Marker({
        position: location,
        map: map
    });
}
```

Só o que precisou foram das coordenadas e, mais adiante, no HTML:
```html
<script async defer src="https://maps.googleapis.com/maps/api/js?key={{ google_maps_api_key }}&callback=initMap"></script>
```
E aí há a presença de uma variável de template jinja2 (o mesmo que Django e Flask usam quando em situações normais).

Foi tudo feito baseado num tutorial do próprio Google. E aí? Fazemos a mesma coisa ou outra solução é mais apropriada?

**Comment by rodrigondec** [comment]
Bem, acho válido isso dai. Porém pra gente (API) só iríamos armazenar a localização. Ver como é o formato disso e validar com o pessoal do @discentes-imd/frontend.
