### ISSUE TITLE
Alterar o readme

### ISSUE THREAD

**Issue by rodrigondec** [bti-imd/IntegraTI-API#2]
Alterar o arquivo readme para explicar como rodar a aplicação flask

**Comment by Mazuh** [comment]
Falta só citar sobre a instalação do bd e qual sgdb o computador deve ter.

(E aí escrevo algumas considerações a serem tomadas, no Linux quem não é familiarizado com py/virtualenv/pip pode ser induzido a alguns erros na hora de instalação.)

**Comment by rodrigondec** [comment]
Seguindo os passos que eu coloquei lá no readme não tem como errar, tanto no linux quanto windows ;)

**Comment by Mazuh** [comment]
Tem, home. kk Já vi nos minicursos vários erros de quem não é acostumado com o mundo Python (inclusive erros meus quando tentei começar sozinho). Mas por um bom tempo, enquanto formos só nós, assim é suficiente. Tô comentando aqui na issue pra deixar documentado a lembrança.

**Comment by Mazuh** [comment]
Hoje à noite irei refazer os passos (troquei hd, lembra?) e checar para erros. No momento, já identifiquei com o Weslen que precisa dizer mais sobre a conexão ao banco de dados. Qual arquivo o usuário precisa mexer, qual sgbd etc.

**Comment by rodrigondec** [comment]
Sobre o banco de dados, a conexão é feita [na linha 10 do config.py](https://github.com/discentes-imd/IntegraTI-API/blob/master/config.py#L10).

O sgbd é MySQL. Pra funcionar corretamente precisa configurar o MySQL na máquina local e criar o database IntegraTI. Não precisa criar as tabelas, apenas o database. Do resto o SQLAlchemy cuida.

Atentar para os parâmetros de login e senha do MySQL na conexão, recomendo todos utilizarem esse dai que está no código.

Coloque no readme tbm a questão do ```python manager.py db init```, ```python manager.py db migrate``` e ```python manager.py db upgrade```. Que são os comandos pra gerenciar as migrações dos models no bd.

**Comment by Mazuh** [comment]
@rodrigondec, descreva melhor o que os comandos do ```python mange.py``` fazem lá no readme.
