### ISSUE TITLE
Caso de uso 03 - Registrar evento

### ISSUE THREAD

**Issue by rodrigondec** [bti-imd/IntegraTI-API#4]
Implementar caso de uso Registrar evento de acordo com a [documentação](https://github.com/bti-imd/IntegraTI-API/wiki/Modelo-Casos-de-Uso-(Eventos)#registrar-evento-csu-03)

- [x] Criar controller de CRUD para event
- [x] Fazer documentação do Swagger
- [x] fazer a lógica do controller

**Comment by felihenrique** [comment]
O que seria criar pagina restful?
Se for a pagina para mostrar eventos, creio que seja tarefa para o frontend.

**Comment by rodrigondec** [comment]
Seria criar o método controller para uma url x. Vou alterar isso, ficou ambíguo mesmo

**Comment by felihenrique** [comment]
Pelo que entendi é criar o controller e associar a rota para obter informações do evento, é isso?

**Comment by rodrigondec** [comment]
Sim, definir a rota e tratar as informações recebidas via POST persistindo o objeto evento.
